In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [7]:
rewards_all_episodes=[]
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
       exploration_rate_threshold = random.uniform(0, 1)
       if exploration_rate_threshold > exploration_rate:
           action = np.argmax(q_table[state,:]) 
       else:
            action = env.action_space.sample()
       new_state, reward, done, info = env.step(action)

       q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
           learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
       state = new_state
       rewards_current_episode += reward 

       if done == True: 
           break

   # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)



In [8]:

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.1550000000000001
2000 :  0.2720000000000002
3000 :  0.3940000000000003
4000 :  0.6530000000000005
5000 :  0.6350000000000005
6000 :  0.6870000000000005
7000 :  0.6540000000000005
8000 :  0.6510000000000005
9000 :  0.6570000000000005
10000 :  0.6550000000000005


********Q-table********

[[0.54902683 0.45559576 0.40594293 0.39573125]
 [0.07825361 0.08981802 0.12034838 0.45310243]
 [0.37430826 0.07013443 0.02741573 0.1101634 ]
 [0.03324371 0.         0.         0.        ]
 [0.5718857  0.37059547 0.4366696  0.24810796]
 [0.         0.         0.         0.        ]
 [0.35349424 0.04397683 0.14686467 0.03475519]
 [0.         0.         0.         0.        ]
 [0.43989847 0.36911161 0.27870728 0.59770921]
 [0.41587931 0.65259523 0.41676768 0.31506378]
 [0.62032566 0.38104786 0.36809706 0.20724852]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40295625 0.42533092 0.74556109 0.

In [9]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
